#!/bin/bash

DN=${1:-0}			#device number
NB=${2:-1024}		#total buffers
RCL=${3:-1}			#recycle 0 = No, >0 = how many cycles until recycle
SPAD=${4:-8}		#total spad items
SPAD_START=${5:-8}	#index of first spad item


if [ !  -e ../AFHBA404 ]; then
	echo "ERROR: did not find ../AFHBA404"
	exit 1
fi

cd ../AFHBA404; sudo ./scripts/stream-to-ramdisk-verify ${DN} ${NB} ${RCL} ${SPAD} ${SPAD_START}