#!/bin/bash

devnum=${1:-0} 
nbuffers=${2:-1024}
overwrite=${3:-1} # 1 = overwite 0 = dont

if [ !  -e ../AFHBA404 ]; then
	echo "ERROR: did not find ../AFHBA404"
	exit 1
fi

total_ramps=0
good_ramps=0
bad_ramps=0
ugly_ramps=0

file="/mnt/afhba.${devnum}/ramp_${devnum}.log"
[ ! -e $file ] || rm $file
err_file="/mnt/afhba.${devnum}/err_${devnum}.log"
[ ! -e $err_file ] || rm $err_file

while read line; do
	if [[ ${line:0:1} == "/" ]] ; then
		result=$(../AFHBA404/FUNCTIONAL_TESTS/checkramp480 < $line)
		#echo -e "\033[93m $result \033[00m "
		(( ++total_ramps ))
		if [[ ${#result} -gt 10 && ${#result} -lt 50 ]]; then
		else
			(( ++bad_ramps ))
			echo "BAD:${total_ramps} ${result}" >> $err_file
		fi
		if (( $total_ramps % 300 == 0 )); then
			echo "Ramps Total: ${total_ramps} Bad: ${bad_ramps}" > $file
		fi
	fi
done < <(cd ../AFHBA404; sudo ./scripts/stream-to-ramdisk-oneshot ${devnum} ${nbuffers} ${overwrite}) 2> /dev/null
bad_per=$(echo "scale=2; 100/${total_ramps}*${bad_ramps}" | bc -l)
echo "Ramps Total: ${total_ramps} Bad: ${bad_ramps} ${bad_per}%" > $file

