#!/bin/bash

devnum=${1:-0} 
nbuffers=${2:-1024}
overwrite=${3:-1} # 1 = overwite 0 = dont

if [ !  -e ../AFHBA404 ]; then
	echo "ERROR: did not find ../AFHBA404"
	exit 1
fi

(
	(cd ../AFHBA404; sudo ./scripts/stream-to-ramdisk-oneshot ${devnum} ${nbuffers} ${overwrite} 2>&1) >stream.log & 
	 wait; echo log file $(ls -l stream.log); echo DATA $(du -sh /mnt/afhba.$1/) 
) &
