#!/bin/bash
UUT=${1}

ACTIVE_CHAN=${ACTIVE_CHAN:-9,10,11}

[ -z $UUT ] && (echo usage: run_bolo_with_host_power_computation UUT [cal] [cap];exit 1)

shift
if [ -z $1 ]; then 
	commands="cap"
else
	commands="$*"
fi

BCC=./user_apps/special/bolo8_cal_cap_loop.py
UPLOAD=./user_apps/acq400/acq400_upload.py
#PB=./user_apps/special/plot_acq2106_123.py
PB=./plot_acq123_sos.py

do_cal() {
$BCC --active_chan=${ACTIVE_CHAN} --fpgpio_strobe=2 --cc=2 --shots=1 $UUT
}

do_cap() {
$BCC --active_chan=${ACTIVE_CHAN} --fpgpio_strobe=2 --cc=1 --shots=1 $UUT
}

do_hostplot() {
$PB $UUT
}


for cmd in $commands; do
	echo UUT: $UUT Command $cmd
	case $cmd in
	cal)
		do_cal;;
	cap)
		do_cap;;
	hostplot)
		do_hostplot;;
	fullcap)
		do_cap
		$UPLOAD --save_data DATA $UUT
		do_hostplot;;
	*)
		echo cmd $cmd not supported;;
	esac
done

